//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BCTONKHO
    {
        public int ID_BCTonKho { get; set; }
        public int ID_Hang { get; set; }
        public int TonDau { get; set; }
        public int SoLuongNhap { get; set; }
        public int SuDung { get; set; }
        public int TonCuoi { get; set; }
    }
}
