//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONDV
    {
        public int ID { get; set; }
        public int ID_Phong { get; set; }
        public System.DateTime NgayGioLap { get; set; }
        public Nullable<double> SoGio { get; set; }
        public string TenKH { get; set; }
        public decimal TongTien { get; set; }
        public Nullable<decimal> TienPhong { get; set; }
        public byte Deleted { get; set; }
    }
}
