//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIPHONG
    {
        public int ID { get; set; }
        public string Ten { get; set; }
        public Nullable<decimal> GiaNgay { get; set; }
        public Nullable<decimal> GiaDem { get; set; }
        public Nullable<int> SoLuong { get; set; }
    }
}
