//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLPhongKaraokeEntities : DbContext
    {
        public QLPhongKaraokeEntities()
            : base("name=QLPhongKaraokeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BCDOANHTHU> BCDOANHTHUs { get; set; }
        public DbSet<BCTONKHO> BCTONKHOes { get; set; }
        public DbSet<CT_BCTONKHO> CT_BCTONKHO { get; set; }
        public DbSet<CT_HDNHAP> CT_HDNHAP { get; set; }
        public DbSet<CT_HOADONDV> CT_HOADONDV { get; set; }
        public DbSet<DATPHONG> DATPHONGs { get; set; }
        public DbSet<HANG> HANGs { get; set; }
        public DbSet<HOADONDV> HOADONDVs { get; set; }
        public DbSet<HOADONNHAP> HOADONNHAPs { get; set; }
        public DbSet<LOAIPHONG> LOAIPHONGs { get; set; }
        public DbSet<PHIEUCHI> PHIEUCHIs { get; set; }
        public DbSet<PHONG> PHONGs { get; set; }
        public DbSet<THAMSO> THAMSOes { get; set; }
    }
}
