//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUCHI
    {
        public int ID { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string NoiDung { get; set; }
        public decimal TongTien { get; set; }
        public string GhiChu { get; set; }
        public byte Deleted { get; set; }
    }
}
